version: '3.4'

services:
  petclinicgolang:
    image: petclinicgolang
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
